describe('template spec', () => {
  it('passes', () => {
    cy.visit('localhost:3000/resources/damage-calculator')
    cy.get('[data-cy="level"]').should('exist')
    cy.get('[data-cy="attack"]').should('exist')
    cy.get('[data-cy="addition"]').should('exist')
    cy.get('[data-cy="enemy"]').should('exist')
    cy.get('[data-cy="base-dmg"]').should('exist').contains('Base Damage: ')
    cy.get('[data-cy="addition-dmg"]').should('exist').contains('Completed Addition Damage: ')

    cy.get('[data-cy="level"]').type(1)
    cy.get('[data-cy="attack"]').type(100)
    cy.get('[data-cy="addition"]').type(100)
    cy.get('[data-cy="enemy"]').select('Beastie Dragon')
    cy.get('[data-cy="base-dmg"]').should('exist').contains('Base Damage: 23')
    cy.get('[data-cy="addition-dmg"]').should('exist').contains('Completed Addition Damage: 23')

    cy.get('[data-cy="addition"]').clear().type(120)
    cy.get('[data-cy="base-dmg"]').should('exist').contains('Base Damage: 23')
    cy.get('[data-cy="addition-dmg"]').should('exist').contains('Completed Addition Damage: 28')

    cy.get('[data-cy="enemy"]').select('Air Combat')
    cy.get('[data-cy="base-dmg"]').should('exist').contains('Base Damage: 19')
    cy.get('[data-cy="addition-dmg"]').should('exist').contains('Completed Addition Damage: 23')

    //invalid Level Data
    cy.get('[data-cy="level"]').clear().type(100)
    cy.get('[data-cy="level"]').should('have.css', 'border-width', '8px')
    cy.get('[data-cy="base-dmg"]').should('exist').contains('Base Damage: 47')
    cy.get('[data-cy="addition-dmg"]').should('exist').contains('Completed Addition Damage: 56')
    cy.get('[data-cy="level"]').clear().type(99)
    cy.get('[data-cy="level"]').should('have.css', 'border-width', '1px')
    cy.get('[data-cy="base-dmg"]').should('exist').contains('Base Damage: 325')
    cy.get('[data-cy="addition-dmg"]').should('exist').contains('Completed Addition Damage: 390')
    //invalid Attack Data
    cy.get('[data-cy="attack"]').clear().type(1000)
    cy.get('[data-cy="attack"]').should('have.css', 'border-width', '8px')
    cy.get('[data-cy="base-dmg"]').should('exist').contains('Base Damage: 325')
    cy.get('[data-cy="addition-dmg"]').should('exist').contains('Completed Addition Damage: 390')
    cy.get('[data-cy="attack"]').clear().type(75)
    cy.get('[data-cy="attack"]').should('have.css', 'border-width', '1px')
    cy.get('[data-cy="base-dmg"]').should('exist').contains('Base Damage: 244')
    cy.get('[data-cy="addition-dmg"]').should('exist').contains('Completed Addition Damage: 293')
    //invalid Addition Data
    cy.get('[data-cy="addition"]').clear().type(99)
    cy.get('[data-cy="addition"]').should('have.css', 'border-width', '8px')
    cy.get('[data-cy="base-dmg"]').should('exist').contains('Base Damage: 244')
    cy.get('[data-cy="addition-dmg"]').should('exist').contains('Completed Addition Damage: 293')
    cy.get('[data-cy="addition"]').clear().type(140)
    cy.get('[data-cy="addition"]').should('have.css', 'border-width', '1px')
    cy.get('[data-cy="base-dmg"]').should('exist').contains('Base Damage: 244')
    cy.get('[data-cy="addition-dmg"]').should('exist').contains('Completed Addition Damage: 341')
  })
})